swagger: "2.0"
info:
  title: Swagger Bear Token API
  version: 1.0.0
  description: APIs for Bear Token authentication
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: Use 'Bearer {token}' format
paths:
  /protected-resource:
    get:
      security:
        - Bearer: []
      description: Retrieve protected resource using Bear Token
      responses:
        200:
          description: Successful access to protected resource
        401:
          description: Unauthorized, Bear Token invalid
